### PR TITLE
Including support for Lodash with $$ wrapper object in map transform

### PR DESCRIPTION
**Pull request by thalesmello**
This pull request includes:

* support for lodash functions with the `_` object
* wrapper object with the `$$` object
* tests for the new functionality
* documentation

### CODE REVIEW

**Comment by danielstjules** [comment]
Looks good! Mind rebasing/squashing? :)

**Comment by thalesmello** [comment]
@danielstjules Done

**Comment by danielstjules** [comment]
Looks good, thanks again! :)

**Comment by thalesmello** [comment]
@danielstjules Did you publish this pull request to npm? I would like to remove my modified version and use the npm one instead.

**Comment by danielstjules** [comment]
Done :)

**Pull request merged**
